spring:
  datasource:
    url: ${{ secrets.AWS_RDS_URL }}
    username: ${{ secrets.AWS_RDS_USERNAME }}
    password: ${{ secrets.AWS_RDS_PASSWORD }}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000